### PR TITLE
Added a few functions to the interaction object

### PR DESCRIPTION
**Pull request by nab138**
**Please describe the changes this PR makes and why it should be merged:**
This allows people to easily reply to interactions. It works exactly the same as message.reply(), you specify the message and the bot will respond to the slash command with it.
Example:
    `client.on("interactionCreate", (interaction) => {
  if (interaction.name === "ping") {
    interaction.reply("pong");
  }
});`
Other functions:
interaction.thinking(): Sends a type 5 reply to discord, making the bot say "<bot> is thinking...".
interaction.edit(): Edits the reply to the interaction. This is the only way to replace "Bot is thinking" with an actual message.
**Status**

- [x] Code changes have been tested against the Discord API, or there are no code changes
- I don't know if typings need updating or how to update them if they do but the code seems to work

**Semantic versioning classification:**

- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by MatteZ02** [comment]
@nab138 Could you update the to match the changes you made. I can do that too if you don't know how.

**Comment by nab138** [comment]
Did you mean update the typings? If so I have no clue how

**Comment by ebiggz** [comment]
@nab138 I really like your direction with this!

I think there's a few tweaks that could be make to take it another step further so I went ahead and took a stab at it in my own fork. I also added updated typings + documentation. 

**Here is the diff:**
https://github.com/nab138/discord.js/compare/master...ebiggz:master?diff=split

**Notable updates are:**
- Added a `.delete()` function for deleting replies to the Interaction
- All functions (`.thinking()`, `.reply()`, `.edit()`, `.delete()`) now return Promises so they can be awaited if desired.
- Supported types for the `input` argument in `.reply()` and `.edit()` are now: message string, array of embeds, or an object containing both. This should give maximum flexibility.
- Added optional `ephemeral` boolean arg to `.reply()` and `.thinking()`. ["Ephemeral" messages](https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionapplicationcommandcallbackdata) are visible only to the command sender
- Updated `.reply()` to support sending additional [Followup Messages](https://discord.com/developers/docs/interactions/slash-commands#followup-messages).
  - To that end, `.reply()` now returns a Promise that resolves a message id which can be used for `.edit()` and `.delete()`
  
**Example:**
```ts
client.on("interactionCreate", async interaction => { 
    if (interaction.name === "ping") { 
        // send initial reply
        await interaction.reply("Pong");

        // send followup
        const messageId = await interaction.reply({
            content: "Follow up message",
            embeds: [new MessageEmbed().setDescription('Follow up test')]
        });
       
        // send another follow up but only visible to the command sender
        await interaction.reply('Ephemeral test', true);

        setTimeout(() => {
            // delete initial reply
            interaction.delete();

            // edit 1st followup
            interaction.edit('Edited follow up message', messageId);
        }, 5000);
    } 
});
```

Apologies for the jumping in out of nowhere on in-progress work... I started tweaking and poking around and before I knew it I was here. @MatteZ02 Let me know if you prefer I make this a different PR on this repo or a PR on @nab138's fork so the tweaks can be rolled into this (Given you find these tweaks acceptable).

**Comment by nab138** [comment]
Wow @ebiggz ! I'm really impressed!

I actually did have a version that returned promises, but I forgot to commit it.
I also had a few other plans but you added them all here (I was working on a more flexible system for embeds, ephemeral messages and a delete function but you covered them)
Your implementation is great and I'm really impressed with all this, its way better then code I could've made

I threw this together as a simple way to send messages to keep my actual code clean but this implementation is much better.
Thanks for doing all this! 

If you open a PR on my fork I will gladly accept it unless you feel opening a PR here would be better.

**Comment by ebiggz** [comment]
@nab138 Sure thing! Your direction with this was great and it inspired me to take it further, so thanks for that. I'll make a PR on your fork 👍

**Comment by MatteZ02** [comment]
This will be very helpful. Ill have to review the changes when i got sufficient time.

**Review by MatteZ02 — APPROVED** [review]

**Comment by MatteZ02** [comment]
@nab138 or @ebiggz any change either of you could do a pr on https://github.com/MatteZ02/discord-interactions with the changes to discord.js example this pr requires?

**Comment by ebiggz** [comment]
@MatteZ02 Here ya go: https://github.com/MatteZ02/discord-interactions/pull/16

**Pull request merged**
